### ISSUE TITLE
Custom Pod Annotations

### ISSUE THREAD

**Issue by mgagliardo91** [authzed/spicedb-operator#106]
I see in the docs (https://docs.authzed.com/spicedb/operator) that there is an option for `extraPodLabels`, but I couldn't find if passing custom annotations was supported via the operator. In our stack, we use custom annotations to be able to do things such as collect prometheus metrics for specific pods, etc. Given that the metrics are exposed on the SpiceDB cluster pods at `:9090/metrics`, we would like to be able to configure the pod to have a few custom annotations that would direct our collector to pick up the OpenMetrics output.

For extra context, we are using Datadog and this is how their Kubernetes collector works. Would it be possible to allow passing through custom annotations to the pods if its not already a capability?

Thanks!

**Comment by ecordell** [comment]
There's a tracking issue for this and similar problems here: https://github.com/authzed/spicedb-operator/issues/61

There are a few options that work today that are outlined in that issue, but there's currently not a simple `extraPodAnnotations` field. That would be a relatively small change, and in line with what `extraPodLabels` are for (we use them for integration with the prometheus operator, which uses labels to know what to scrape).

**Comment by mgagliardo91** [comment]
@ecordell yea, I would like to avoid modifying the CRDs manually - we are pretty heavy on GitOps and want to avoid any manual touching of K8s CRDs (we rely pretty heavily on Helm). I think we can wait for the `extraPodAnnotations` which should be enough of a customization for our needs - do you think that is something that could be prioritized?

Thanks for the fast reply btw!

**Comment by mgagliardo91** [comment]
@ecordell I went ahead and created a PR (https://github.com/authzed/spicedb-operator/pull/107) to get the annotations working. Mind taking a look when you have time?

**Comment by mstrYoda** [comment]
Hi all, what is the status of this issue?

We also need this functionality to disable istio-proxy sidecar on authzed migrator pod 🙏

**Comment by ecordell** [comment]
@mstrYoda The feature is in main but not yet in a release, that should come very soon

**Comment by ecordell** [comment]
Fixed by https://github.com/authzed/spicedb-operator/pull/107
