### ISSUE TITLE
Running the guide to setup the operator results in UNAVAILABLE of spice on port 50053

### ISSUE THREAD

**Issue by hermanbanken** [authzed/spicedb-operator#109]
I was following this guide https://docs.authzed.com/spicedb/operator.
Nit: I needed to use `brew install authzed/tap/zed` instead of `brew install zed` but this still didn't work due to some Ruby error in brew (might be unrelated). `go install github.com/authzed/zed/cmd/zed@latest` did work for me though.

Then, when following the guide by using these approximate commands, I get the error at the end.

```bash
$ kubectl apply --server-side -k github.com/authzed/spicedb-operator/config

$ kubectl apply --server-side -f - <<EOF
apiVersion: authzed.com/v1alpha1
kind: SpiceDBCluster
metadata:
  name: dev
spec:
  config:
    image: ghcr.io/authzed/spicedb:v1.14.1
    datastoreEngine: memory
  secretName: dev-spicedb-config
---
apiVersion: v1
kind: Secret
metadata:
  name: dev-spicedb-config
stringData:
  preshared_key: "averysecretpresharedkey"
EOF

$ zed schema write <(cat << EOF
/** user represents a user */
definition user {}

/** document represents a document with access control */
definition document {
  /** reader indicates that the user is a reader on the document */
  relation reader: user
}
EOF
)

$ zed context set local localhost:50051 "averysecretpresharedkey" --insecure

$ zed relationship create document:test reader user:herman
GhUKEzE2Njg3NjkxMDMwODU3NjY2OTY=

$ zed permission check --explain document:test reader user:herman
11:54AM INF debugging requested on check
11:54AM WRN No debuging information returned for the check
Error: rpc error: code = Unavailable desc = last connection error: connection error: desc = "transport: Error while dialing dial tcp 10.32.4.235:50053: connect: connection refused"
Usage:
  zed permission check <resource:id> <permission> <subject:id> [flags]
```

I've verified that the pod for the cluster is running, that it has said ports configured. Somehow it can't reach itself (it has IP 10.32.4.235).

**Comment by hermanbanken** [comment]
Running 
```
kubectl port-forward deployment/dev-spicedb 50051:50051 50053:50053 &
nc localhost 50053
```
gives me
```
E1118 12:02:01.013496   54895 portforward.go:400] an error occurred forwarding 50053 -> 50053: error forwarding port 50053 to pod e405062193775c6a825c750ad2f8b031d6b731831b76838c24fc877681080c5c, uid : failed to execute portforward in network namespace "/var/run/netns/cni-0c7a52f1-04ea-7998-d5fb-b92aef883aa3": failed to connect to localhost:50053 inside namespace "e405062193775c6a825c750ad2f8b031d6b731831b76838c24fc877681080c5c", IPv4: dial tcp4 127.0.0.1:50053: connect: connection refused IPv6 dial tcp6 [::1]:50053: connect: cannot assign requested address
```

So maybe the problem is some cni IPv6 issue and not related to SpiceDB, but it points at an issue with deploying in (default) GKE maybe?

**Comment by vroldanbet** [comment]
The error suggests this is happening on port 50053, which is dispatch. Can you check the SpiceDB deployment the operator created and see what ENVs it injected for dispatch?

**Comment by hermanbanken** [comment]
Ah, that seems to be a good lead, the pod created by the operator has `SPICEDB_DISPATCH_CLUSTER_ENABLED:  false`. So indeed, dispatch seems disabled.

There is only 1 pod:
```
-> % kubectl get pods | grep spice
dev-spicedb-7f56c44c9c-jfj4p                                    1/1     Running            0               71m
```

**Comment by hermanbanken** [comment]
After scaling up the deployment to two instances it seems to not error directly, but instead it hangs, and errors with 
```
Error: rpc error: code = Unavailable desc = failed to receive server preface within timeout
```
after a while.

**Comment by hermanbanken** [comment]
Somehow I managed to get it to work at some point... But I think the operator setup guide could use some tweaking/testing.

**Comment by vroldanbet** [comment]
@hermanbanken did you figure out what was wrong in the setup so we can adjust the guide?

**Comment by hermanbanken** [comment]
No I don't know for sure. I can test this on Monday with a fresh cluster, as I know better understand where to find debug information.

The operator is very silent, I found the status info in the crd resources, which I didn't pay too close attention to before.

For example when trying to use CockroachDB I didn't notice it hang on migrate, leading me to investigate the datastore CA TLS flags.

I think the error messages in the CRDs could be mentioned somewhere in the docs in an operator _troubleshooting_ section. And maybe pick some common examples of configuration mistakes and document in more detail in the guide how to resolve them.
