### ISSUE TITLE
Contributions require both DCO and CLA

### ISSUE THREAD

**Issue by jawnsy** [authzed/spicedb-operator#239]
The contribution guidelines mention that we need to sign the Developer Certificate of Origin, however, the repository also seems to require a CLA.

* https://github.com/authzed/spicedb-operator/blob/main/CONTRIBUTING.md#legal-requirements and https://github.com/authzed/spicedb-operator/blob/main/DCO
* https://github.com/authzed/spicedb-operator/blob/main/.github/workflows/cla.yaml

Probably only one of these is necessary, especially because GitHub's terms of service already has an `inbound=outbound` policy: https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license

**Comment by ecordell** [comment]
@jzelinskie and I were just discussing this today. The plan is to keep the DCO around, require signing the CLA, but not require sign-off of commits (which is a pain)
