### ISSUE TITLE
v1.14 version not semver compatible (no patch)

### ISSUE THREAD

**Issue by to266** [authzed/spicedb-operator#303]
Previous releases worked wonderfully with flux through the [OCI repository](https://github.com/fluxcd/source-controller/blob/main/docs/spec/v1beta2/ocirepositories.md#semver-example), however [v1.14](https://github.com/authzed/spicedb-operator/releases/tag/v1.14) did not follow semver by not having patch identifier, and thus flux does not pick it up automatically.

A fix would be to just release v.1.14.0 with exactly the same content, except with the new tag, maybe?

**Comment by vroldanbet** [comment]
Whoops, our apologies! I've released a new version that follows semver, thanks for reporting!
https://github.com/authzed/spicedb-operator/releases/tag/v1.14.0
