### ISSUE TITLE
Does spicedb-operator support setting multiple preshared keys?

### ISSUE THREAD

**Issue by galenwarren** [authzed/spicedb-operator#305]
Support for multiple preshared keys [exists](https://github.com/authzed/spicedb/issues/288) in spicedb, but I only see documentation for setting a single preshared key, via ```preshared_key``` in the config secret.

Can multiple keys be set? This would be useful for key rotation. 

Thanks.

**Comment by ecordell** [comment]
Yes, the `preshard_key` can be given multiple keys as a comma-separated list just like on the SpiceDB command line, i.e. `preshared_key: key1,key2` etc.

Closing this but feel free to re-open if you find issues with setting multiple preshared keys
