### ISSUE TITLE
v1.16.0: configuration file /opt/operator/config.yaml missing

### ISSUE THREAD

**Issue by zd9KgA** [authzed/spicedb-operator#327]
The operator fails at start, because the specified configuration file cannot be accessed (panic).

**Comment by ecordell** [comment]
Thanks for the report, the new release process has broken this. 

While I work on fixing it, you can optionally mount this file: https://github.com/authzed/spicedb-operator/blob/main/validated-update-graph.yaml at `/opt/operator/config.yaml` to get it working.

**Comment by zd9KgA** [comment]
Many thanks for the swift response. I'll stick to v1.15.0 for the time being and wait for the fix. :-)

**Comment by ecordell** [comment]
1.16.1 is out, with the graph included in the release manifests. Sorry about that!

**Comment by zd9KgA** [comment]
Many thanks, Evan. Works fine now.
