### ISSUE TITLE
Update `stable` release channels with recent releases

### ISSUE THREAD

**Issue by frekw** [authzed/spicedb-operator#335]
Hi!

Just noticed that there are a couple of releases of SpiceDB that are not yet in the update graph. I could have a go at adding them, but I'm unsure what to do about the migrations that may be needed.

**Comment by ecordell** [comment]
Hi @frekw - sorry for the delay here.

We merged https://github.com/authzed/spicedb-operator/pull/331 a while ago and discovered some issues with it while testing, which has delayed a release here. We'll work on getting those issues fixed and the newer spicedb releases available soon.

**Comment by frekw** [comment]
@ecordell no worries at all! Happy to hear you're on the ball :pray:

**Comment by viqueen** [comment]
Hei hei 👋 
I came by to see if there are any updates, we're hoping to get on the latest version of SpiceDB

**Comment by croemmich** [comment]
@ecordell we'd love to update for some memory fixes and LookupResources v2, but we're stuck on 1.31. Would it be feasible to add a `mainline` or similar channel that has all releases in it? This would make testing new versions in our dev/test clusters easier as well.

**Comment by ecordell** [comment]
#339 fixes the problem mentioned above. Once that merges we'll add the newer releases and them tested and merged. Thanks for your patience here!

**Comment by ecordell** [comment]
https://github.com/authzed/spicedb-operator/releases/tag/v1.17.0 is out with support for spicedb up to 1.38.0! 

Thanks for everyone's patience with this!
