### ISSUE TITLE
Add option for toleration, node selector, affinity, and topologySpreadConstraints

### ISSUE THREAD

**Issue by djoo-ce** [authzed/spicedb-operator#98]
Right now, there is no config option in `SpiceDBCluster` for setting
* tolerations
* nodeSelector
* affinity/anti-affinity
* topologySpreadConstraints
Is there any plan in the future to support these configs in the operator?

**Comment by ecordell** [comment]
Yes, these are all things we'd like to support. The current discussion is happening in #61 - feel free to chime in there, otherwise we'll keep these examples in mind when we look at addressing #61.

**Comment by ecordell** [comment]
This is now possible in in [v1.2.0](https://github.com/authzed/spicedb-operator/releases/tag/v1.2.0)
